import jsPDF from 'jspdf';
import type { ResumeAnalysis } from '@/types';

export function generatePDFReport(analysis: ResumeAnalysis, fileName: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;
  const lineHeight = 6;

  const addSection = (title: string, items: string[]) => {
    if (items.length === 0) return;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 64, 175);
    doc.text(title, 20, y);
    y += lineHeight;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);

    items.forEach((item) => {
      const splitText = doc.splitTextToSize(`• ${item}`, pageWidth - 50);
      splitText.forEach((line: string) => {
        if (y > 280) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, 25, y);
        y += lineHeight - 1;
      });
    });
    y += 3;
  };

  const addScoreBox = (label: string, score: number, x: number, w: number) => {
    doc.setFillColor(240, 240, 245);
    doc.roundedRect(x, y - 5, w, 25, 3, 3, 'F');
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(label, x + w / 2, y + 2, { align: 'center' });
    doc.setFontSize(16);
    doc.setTextColor(30, 64, 175);
    doc.text(score.toString(), x + w / 2, y + 14, { align: 'center' });
  };

  doc.setFillColor(30, 64, 175);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Resume Analyzer Report', 20, 18);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`, 20, 28);
  doc.text(`File: ${fileName}`, 20, 35);

  y = 55;

  addScoreBox('Overall Score', analysis.overallScore, 20, 80);
  addScoreBox('ATS Score', analysis.atsScore, 110, 80);
  y += 30;

  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  const whyText = doc.splitTextToSize(analysis.whyThisScore, pageWidth - 40);
  whyText.forEach((line: string) => {
    doc.text(line, 20, y);
    y += lineHeight;
  });
  y += 5;

  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, pageWidth - 20, y);
  y += 8;

  addSection('Strengths', analysis.strengths);
  addSection('Weaknesses', analysis.weaknesses);

  if (analysis.missingSkills.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 64, 175);
    doc.text('Missing Skills', 20, y);
    y += lineHeight;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(analysis.missingSkills.join(', '), 25, y);
    y += lineHeight + 3;
  }

  addSection('Recommendations', analysis.recommendations);

  if (analysis.projectFeedback.length > 0) {
    if (y > 220) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 64, 175);
    doc.text('Project Evaluations', 20, y);
    y += lineHeight + 2;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);

    analysis.projectFeedback.forEach((project) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }
      doc.setFont('helvetica', 'bold');
      doc.text(`${project.name} (Score: ${project.score})`, 25, y);
      y += lineHeight - 1;
      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(project.evaluation, pageWidth - 55);
      lines.forEach((line: string) => {
        doc.text(line, 30, y);
        y += lineHeight - 1;
      });
      y += 2;
    });
    y += 3;
  }

  if (analysis.redFlags.length > 0) {
    if (y > 200) {
      doc.addPage();
      y = 20;
    }
    doc.setFillColor(255, 243, 224);
    doc.roundedRect(20, y - 5, pageWidth - 40, 8 + analysis.redFlags.length * 12, 3, 3, 'F');

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(180, 83, 9);
    doc.text('Recruiter Concerns', 25, y + 2);
    y += lineHeight;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120, 60, 20);

    analysis.redFlags.forEach((flag) => {
      if (y > 280) {
        doc.addPage();
        y = 20;
      }
      const line = doc.splitTextToSize(`• ${flag.issue}: ${flag.whyItMatters}`, pageWidth - 55);
      line.forEach((l: string) => {
        doc.text(l, 30, y);
        y += 5;
      });
    });
    y += 5;
  }

  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.text('Generated by AI Resume Analyzer - Built for placement-ready portfolios', pageWidth / 2, 285, { align: 'center' });

  return doc;
}

export function downloadAnalysisPDF(analysis: ResumeAnalysis, fileName: string) {
  const doc = generatePDFReport(analysis, fileName);
  const safeFileName = fileName.replace(/\.pdf$/i, '') || 'resume';
  doc.save(`${safeFileName}_analysis_${new Date().toISOString().split('T')[0]}.pdf`);
}
